resources:
  - name: code
    type: git
    source:
      uri: https://github.com/doughoke/concourse-windows-example-cicd.git
      branch: master
jobs:
  - name: build
    plan:
    - in_parallel:
      - get: code
        trigger: true
    - task: build
      config:
        platform: windows
        inputs:
          - name: code
        outputs:
          - name: output
        run:
          path: runDockerImage.bat
        params:
          DOCKER_IMAGE: mcr.microsoft.com/dotnet/framework/sdk:4.7.2
          WORKING_DIRECTORY: code
          SCRIPT_PATH: build.bat
          ENV_ENVIRONMENT_VARIABLE: 1
